# Generated by Django 3.0.3 on 2020-11-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Выберите город. Предполагается, что пользователь это сущность, имеющая отношение к городу. Пользователь может иметь несколько точек в городе с одинаковыми ценами. Если сеть федеральная, то в каждом городе свой пользователь', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
