# Generated by Django 3.0.3 on 2020-03-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите наименование вида деятельности', max_length=200)),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название постащика, м.б. зарегистрированное или нет', max_length=200, unique=True)),
                ('primary_activity', models.ForeignKey(help_text='Выберите основной вид деятельности', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_activity', to='suppliers.Activity')),
                ('secondary_activity', models.ManyToManyField(help_text='Выберите дополнительные виды деятельности', related_name='secondary_activity', to='suppliers.Activity')),
            ],
            options={
                'verbose_name': 'Поставщик услуг/материалов',
                'verbose_name_plural': 'Поставщики услуг/материалов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Простонародное название производителя материала. Например, Кощаковский, Чайковский и т.д.', max_length=200)),
                ('name', models.CharField(help_text='Полное название производителя материала. Например, Кощаковский, Чайковский и т.д.', max_length=200, unique=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите бренд (например, Wienerberger), если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.Brand')),
                ('city', models.ForeignKey(blank=True, help_text='Выберите город', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.City')),
            ],
            options={
                'verbose_name': 'Производитель материала',
                'verbose_name_plural': 'Производители материалов',
                'ordering': ('name',),
            },
        ),
    ]
