# Generated by Django 3.0.3 on 2020-09-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='primary_activity',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='secondary_activity',
        ),
    ]
