# Generated by Django 3.0.2 on 2020-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkSand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('quarry', 'Карьерный'), ('river', 'Речной')], default='quarry', help_text='Тип песка', max_length=6)),
                ('weight', models.IntegerField(help_text='Масса песка в грузовике')),
            ],
            options={
                'verbose_name': 'Песок россыпью в самосвалах',
                'verbose_name_plural': 'Песок россыпью в самосвалах',
                'ordering': ('name', 'weight'),
            },
        ),
    ]
