# Generated by Django 3.0.3 on 2020-03-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите основной бренд, например, Wienerberger', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Основной бренд',
                'verbose_name_plural': 'Основные бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubBrand_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите торговую марку внутри бренда, например, Porotherm и т.д.', max_length=200, unique=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.Brand')),
            ],
            options={
                'verbose_name': 'Подбренд 1)',
                'verbose_name_plural': 'Подбренды 1)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubBrand_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите индекс серии товаров внутри торговой марки что внутри бренда, если она есть', max_length=200, unique=True)),
                ('sub_brand_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.SubBrand_1')),
            ],
            options={
                'verbose_name': 'Подбренд 2)',
                'verbose_name_plural': 'Подбренды 2)',
                'ordering': ('name',),
            },
        ),
    ]
