# Generated by Django 3.0.3 on 2020-11-05 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal', '0002_auto_20201104_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='administrator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, администрирующий данное юрлицо в системе'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='INN',
            field=models.IntegerField(unique=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='form',
            field=models.CharField(blank=True, choices=[('e', 'ИП'), ('l', 'ООО'), ('c', 'АО')], default='l', max_length=1, verbose_name='Организационно-правовая форма'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
