# Generated by Django 3.0.3 on 2020-06-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('materials', '0002_auto_20200317_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('roof_covering', 'Кровельное покрытие'), ('soffit', 'Соффит (подшивка карниза)'), ('facade_cladding', 'Облицовка фасада'), ('wall', 'Стеновой материал'), ('socle_facing', 'Специально (или идеально) для облицовки цоколя')], default='roof_covering', help_text='Назначение материала', max_length=20)),
            ],
            options={
                'verbose_name': 'Назначение материала',
                'verbose_name_plural': 'Назначения материалов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RoofCoverType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Идентификатор', max_length=200, unique=True)),
                ('identifier', models.CharField(blank=True, help_text='Наименование', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfbearingStoneProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200)),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Производитель материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Manufacturer')),
                ('use', models.ManyToManyField(help_text='Выберите область применения данного материала', to='materials.MaterialUse')),
            ],
        ),
        migrations.CreateModel(
            name='Siding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('metal', 'Металл'), ('wood', 'Дерево'), ('vinyl', 'Винил')], default='metal', help_text='Материал', max_length=20)),
                ('alternative_name', models.CharField(blank=True, choices=[('block_house', 'Деревянный блок-хаус'), ('batten', 'Деревянная вагонка')], help_text='Альтернативное название', max_length=20, null=True)),
                ('texture', models.URLField(help_text='Путь к текстуре')),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите главный бренд, например, Wienerberger', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.Brand')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Производитель материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Manufacturer')),
                ('use', models.ManyToManyField(help_text='Выберите область применения данного материала', to='materials.MaterialUse')),
            ],
        ),
        migrations.CreateModel(
            name='SelfbearingStoneUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200)),
                ('texture', models.URLField(help_text='Путь к текстуре')),
                ('product_line', models.ForeignKey(blank=True, help_text='Продуктовая линейка', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.SelfbearingStoneProductLine')),
            ],
        ),
        migrations.CreateModel(
            name='Plaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.URLField(help_text='Путь к текстуре')),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите главный бренд, например, Wienerberger', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.Brand')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Производитель материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Manufacturer')),
                ('use', models.ManyToManyField(help_text='Выберите область применения данного материала', to='materials.MaterialUse')),
            ],
        ),
        migrations.CreateModel(
            name='MetalTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.URLField(help_text='Путь к текстуре')),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите главный бренд, например, Wienerberger', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.Brand')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Производитель материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='FlexibleTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture', models.URLField(help_text='Путь к текстуре')),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите главный бренд, например, Wienerberger', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.Brand')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Производитель материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Manufacturer')),
            ],
        ),
    ]
