# Generated by Django 3.0.3 on 2020-06-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_flexibletile_materialuse_metaltile_plaster_roofcovertype_selfbearingstoneproductline_selfbearingston'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoofCoverMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Кровельный материал',
                'verbose_name_plural': 'Кровлельные материалы',
                'ordering': ('material_type', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='metaltile',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='metaltile',
            name='manufacturer',
        ),
        migrations.AlterModelOptions(
            name='roofcovertype',
            options={'ordering': ('name',), 'verbose_name': 'Тип кровельного материала', 'verbose_name_plural': 'Типы кровельных материалов'},
        ),
        migrations.AlterField(
            model_name='roofcovertype',
            name='identifier',
            field=models.CharField(blank=True, help_text='Идентификатор', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='roofcovertype',
            name='name',
            field=models.CharField(blank=True, help_text='Наименование', max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='FlexibleTile',
        ),
        migrations.DeleteModel(
            name='MetalTile',
        ),
        migrations.AddField(
            model_name='roofcovermaterial',
            name='material_type',
            field=models.ForeignKey(blank=True, help_text='Тип материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.RoofCoverType'),
        ),
    ]
