# Generated by Django 3.0.3 on 2020-06-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20200603_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='roofcovermaterial',
            name='texture',
            field=models.URLField(default='http://asd.ru', help_text='Путь к текстуре'),
        ),
    ]
