# Generated by Django 3.0.3 on 2020-06-03 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_roofcovermaterial_texture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfbearingstoneunit',
            name='product_line',
        ),
        migrations.DeleteModel(
            name='SelfbearingStoneProductLine',
        ),
        migrations.DeleteModel(
            name='SelfbearingStoneUnit',
        ),
    ]
