# Generated by Django 3.0.3 on 2020-06-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('materials', '0006_auto_20200603_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoneProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200)),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Производитель материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Manufacturer')),
                ('use', models.ManyToManyField(help_text='Выберите область применения данного материала', to='materials.MaterialUse')),
            ],
        ),
        migrations.CreateModel(
            name='StoneUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200)),
                ('texture', models.URLField(help_text='Путь к текстуре')),
                ('product_line', models.ForeignKey(blank=True, help_text='Продуктовая линейка', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.StoneProductLine')),
            ],
        ),
    ]
