# Generated by Django 3.0.3 on 2020-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_stoneproductline_stoneunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stoneproductline',
            options={'ordering': ('name',), 'verbose_name': 'Продуктовая линейка кирпича (блока)', 'verbose_name_plural': 'Продуктовые линейки кирпичей (блоков)'},
        ),
        migrations.AlterModelOptions(
            name='stoneunit',
            options={'ordering': ('name', 'product_line'), 'verbose_name': 'Элемент из продуктовой линейки кирпича (блока)', 'verbose_name_plural': 'Элементы из продуктовых линеей кирпичей (блоков)'},
        ),
        migrations.AddField(
            model_name='materialuse',
            name='identifier',
            field=models.CharField(blank=True, help_text='Идентификатор', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='materialuse',
            name='name',
            field=models.CharField(blank=True, help_text='Наименование', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='plaster',
            name='texture',
            field=models.URLField(default='http://asd.ru', help_text='Путь к текстуре'),
        ),
        migrations.AlterField(
            model_name='stoneunit',
            name='texture',
            field=models.URLField(default='http://asd.ru', help_text='Путь к текстуре'),
        ),
    ]
