# Generated by Django 3.0.3 on 2020-06-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20200603_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibleTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200, unique=True)),
                ('texture', models.URLField(default='http://asd.ru', help_text='Путь к текстуре')),
            ],
            options={
                'verbose_name': 'Гибкая черепица',
                'verbose_name_plural': 'Гибкая черепица',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MetalTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Наименование', max_length=200, unique=True)),
                ('texture', models.URLField(default='http://asd.ru', help_text='Путь к текстуре')),
            ],
            options={
                'verbose_name': 'Металлочерепица',
                'verbose_name_plural': 'Металлочерепица',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='RoofCoverMaterial',
        ),
    ]
