# Generated by Django 2.1.4 on 2019-11-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockwallmaterialpriceposition',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialUnit'),
        ),
    ]
