# Generated by Django 2.1.4 on 2019-11-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите бренд продавца', max_length=200, unique=True)),
                ('ownership_form', models.CharField(choices=[('p', 'Частное лицо'), ('c', 'Компания')], default='p', help_text='Выберите форму собственности', max_length=1)),
            ],
            options={
                'verbose_name': 'Поставщик услуг/материалов',
                'verbose_name_plural': 'Поставщики услуг/материалов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProviderActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Введите наименование вида деятельности', max_length=20)),
            ],
            options={
                'verbose_name': 'Доступный вид деятельности',
                'verbose_name_plural': 'Доступные виды деятельности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProviderOutlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(help_text='Введите уточняющее название офиса или торговой точки. Например, Офис на Московской ', max_length=200)),
                ('information', models.TextField(help_text='Контакты, адрес и т.д. продавца', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaxSystemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Введите наименование системы налогообложения', max_length=20)),
            ],
            options={
                'verbose_name': 'Система налогообложения',
                'verbose_name_plural': 'Системы налогообложения',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='sellershop',
            name='city',
        ),
        migrations.RemoveField(
            model_name='sellershop',
            name='name',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('name',), 'verbose_name': 'Область применения материала', 'verbose_name_plural': 'Области применения материалов'},
        ),
        migrations.AlterModelOptions(
            name='bindersolutiontype',
            options={'ordering': ('name',), 'verbose_name': 'Тип связующего раствора', 'verbose_name_plural': 'Типы связующих растворов'},
        ),
        migrations.AlterModelOptions(
            name='materialbrand',
            options={'ordering': ('name',), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ('name',), 'verbose_name': 'Производитель материала', 'verbose_name_plural': 'Производители материалов (конкретные заводы)'},
        ),
        migrations.AlterModelOptions(
            name='rockmatherialtech',
            options={'ordering': ('name',), 'verbose_name': 'Технология производства материала', 'verbose_name_plural': 'Технологии производства материалов'},
        ),
        migrations.AlterModelOptions(
            name='trademark',
            options={'ordering': ('name',), 'verbose_name': 'Торговая марка', 'verbose_name_plural': 'Торговые марки'},
        ),
        migrations.AlterModelOptions(
            name='trademarkseries',
            options={'ordering': ('name',), 'verbose_name': 'Товарная серия', 'verbose_name_plural': 'Товарные серии (какой-либо марки)'},
        ),
        migrations.AlterModelOptions(
            name='wallreinforcementtype',
            options={'ordering': ('name',), 'verbose_name': 'Тип армирования', 'verbose_name_plural': 'Типы армирования'},
        ),
        migrations.RemoveField(
            model_name='rockwallmatherialpriceposition',
            name='shop',
        ),
        migrations.AddField(
            model_name='application',
            name='identifier',
            field=models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='bindersolutiontype',
            name='identifier',
            field=models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='rockmatherialtech',
            name='identifier',
            field=models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='wallreinforcementtype',
            name='identifier',
            field=models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Введите город', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='materialbrand',
            name='name',
            field=models.CharField(help_text='Введите бренд, например, Wienerberger', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(help_text='Введите производителя материала. Например, Кощаковский завод, Чайковский и т.д.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='name',
            field=models.CharField(help_text='Введите торговую марку, например, Porotherm, Kerama и т.д.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='trademarkseries',
            name='name',
            field=models.CharField(help_text='Введите название серии товаров, если она есть', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wallreinforcementtype',
            name='name',
            field=models.CharField(help_text='Введите тип армирования', max_length=100),
        ),
        migrations.DeleteModel(
            name='SellerBrand',
        ),
        migrations.DeleteModel(
            name='SellerShop',
        ),
        migrations.AddField(
            model_name='provideroutlet',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City'),
        ),
        migrations.AddField(
            model_name='provideroutlet',
            name='name',
            field=models.ForeignKey(help_text='Выберите поставщика, которому принадлежит этот офис,торговая точка', on_delete=django.db.models.deletion.CASCADE, to='catalog.Provider'),
        ),
        migrations.AddField(
            model_name='provider',
            name='primary_activity',
            field=models.ForeignKey(help_text='Выберите основной вид деятельности', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_activity', to='catalog.ProviderActivityType'),
        ),
        migrations.AddField(
            model_name='provider',
            name='secondary_activity',
            field=models.ManyToManyField(help_text='Выберите дополнительные виды деятельности', related_name='secondary_activity', to='catalog.ProviderActivityType'),
        ),
        migrations.AddField(
            model_name='provider',
            name='tax_system',
            field=models.ManyToManyField(help_text='Выберите применяемые Вами системы налообложения (можно несколько)', to='catalog.TaxSystemType'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialpriceposition',
            name='outlet',
            field=models.ForeignKey(default='default_identifiter', on_delete=django.db.models.deletion.CASCADE, to='catalog.ProviderOutlet'),
        ),
    ]
