# Generated by Django 2.1.4 on 2019-11-08 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20191107_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='RockWallMaterialUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of this rock wall material (e.g. Blue midnight)', max_length=200)),
                ('a_size', models.IntegerField()),
                ('b_size', models.IntegerField()),
                ('c_size', models.IntegerField()),
                ('thermal_conductivity', models.IntegerField(help_text='Введите коэффициент теплопроводности')),
                ('type_size', models.CharField(choices=[('bl', 'Блок'), ('br', 'Кирпич')], default='br', help_text='Тип материала по размеру: блок или кирпич', max_length=2)),
                ('primary_or_additional', models.CharField(choices=[('p', 'Основной'), ('a', 'Доборный')], default='p', help_text='Тип элемента: основной или доборный', max_length=1)),
                ('application', models.ManyToManyField(help_text='Выберите область применения материала', to='catalog.Application')),
                ('binding_solution', models.ManyToManyField(help_text='Выберите тип связующего для данного материала', to='catalog.BinderSolutionType')),
                ('reinforcement_type', models.ManyToManyField(help_text='Выберите тип армирования для данного материала', to='catalog.WallReinforcementType')),
            ],
            options={
                'verbose_name': 'Единица каменного материала',
                'verbose_name_plural': 'Единицы каменных материалов',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='rockwallmatherialunit',
            name='application',
        ),
        migrations.RemoveField(
            model_name='rockwallmatherialunit',
            name='binding_solution',
        ),
        migrations.RemoveField(
            model_name='rockwallmatherialunit',
            name='reinforcement_type',
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ('name',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='provideroutlet',
            options={'ordering': ('name',), 'verbose_name': 'Торговая точка/офис', 'verbose_name_plural': 'Тороговые точки/офисы'},
        ),
        migrations.AlterModelOptions(
            name='rockwallmaterialpriceposition',
            options={'ordering': ('name',), 'verbose_name': 'Ценовая позиция', 'verbose_name_plural': 'Ценовые позиции'},
        ),
        migrations.AddField(
            model_name='provideroutlet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provideroutlet',
            name='local_name',
            field=models.CharField(blank=True, help_text='Введите уточняющее название офиса или торговой точки. Например, Офис на Московской ', max_length=200),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialpriceposition',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialUnit'),
        ),
        migrations.RenameModel(
            old_name='RockWallMatherialPricePosition',
            new_name='RockWallMaterialPricePosition',
        ),
        migrations.DeleteModel(
            name='RockWallMatherialUnit',
        ),
    ]
