# Generated by Django 2.1.4 on 2019-11-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rockwallmaterialpriceposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialpriceposition',
            name='outlet',
        ),
        migrations.AlterField(
            model_name='rockwallmaterialpriceposition',
            name='name',
            field=models.CharField(help_text='Enter a name of this rock wall material (e.g. Blue midnight)', max_length=200),
        ),
    ]
