# Generated by Django 3.0.2 on 2020-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200228_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RockWallMaterialPricePosition',
        ),
    ]
