# Generated by Django 2.1.4 on 2019-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите класс В', max_length=200)),
            ],
            options={
                'verbose_name': 'Класс В',
                'verbose_name_plural': 'Классы В',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите марку D', max_length=200)),
            ],
            options={
                'verbose_name': 'Марка D',
                'verbose_name_plural': 'Марки D',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите марку М', max_length=200)),
            ],
            options={
                'verbose_name': 'Марка М',
                'verbose_name_plural': 'Марки М',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RockWallMaterialStandardSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите общепринятую классификацию размера или название', max_length=200)),
                ('a_size', models.IntegerField(blank=True)),
                ('b_size', models.IntegerField(blank=True)),
                ('c_size', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Размер каменного материала',
                'verbose_name_plural': 'Размеры каменных материалов',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='provideractivitytype',
            name='identifier',
            field=models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='a_size',
            field=models.IntegerField(blank=True, help_text='Введите размеры, если они нестандарнтые'),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='b_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='c_size',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='name',
            field=models.CharField(help_text='Введите общепринятое название данного материала', max_length=200),
        ),
        migrations.AlterField(
            model_name='taxsystemtype',
            name='identifier',
            field=models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='wallreinforcementtype',
            name='identifier',
            field=models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='class_b',
            field=models.ManyToManyField(blank=True, help_text='Выберите стандартный класс В для данного материала, если есть', to='catalog.ClassB'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='mark_d',
            field=models.ManyToManyField(blank=True, help_text='Выберите стандартную марку D для данного материала, если есть', to='catalog.MarkD'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='mark_m',
            field=models.ManyToManyField(blank=True, help_text='Выберите стандартную марку М для данного материала, если есть', to='catalog.MarkM'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='standard_size',
            field=models.ManyToManyField(blank=True, help_text='Выберите тип стандартного размера, если есть', to='catalog.RockWallMaterialStandardSize'),
        ),
    ]
