# Generated by Django 3.0.2 on 2020-02-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200218_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockwallmaterialcolloquialname',
            name='body_type',
            field=models.CharField(choices=[('solid', 'Полнотелый'), ('hollow', 'Пустотелый')], default='solid', help_text='Пустотелый или полнотелый', max_length=6),
        ),
    ]
