# Generated by Django 3.0.3 on 2020-02-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200226_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите основной бренд, например, Wienerberger', max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Основоной бренд',
                'verbose_name_plural': 'Основоные бренды',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubBrand_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите торговую марку внутри бренда, например, Porotherm и т.д.', max_length=200, unique=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Brand')),
            ],
            options={
                'verbose_name': 'Подбренд 1)',
                'verbose_name_plural': 'Подбренды 1)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SubBrand_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите индекс серии товаров внутри торговой марки что внутри бренда, если она есть', max_length=200, unique=True)),
                ('sub_brand_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.SubBrand_1')),
            ],
            options={
                'verbose_name': 'Подбренд 2)',
                'verbose_name_plural': 'Подбренды 2)',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='factory',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите бренд (например, Wienerberger), если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите главный бренд, например, Wienerberger', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='sub_brand_1',
            field=models.ForeignKey(blank=True, help_text='Выберите наименование внутри бренда (Подбренд 1, если есть), например,  Porotherm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.SubBrand_1'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='sub_brand_2',
            field=models.ForeignKey(blank=True, help_text='Выберите индекс внутри наименования (Подбренд 2, если есть), например, 44 для поротерма', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.SubBrand_2'),
        ),
    ]
