# Generated by Django 2.1.4 on 2019-11-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191112_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassB',
            new_name='ClassBLight',
        ),
        migrations.AlterModelOptions(
            name='classblight',
            options={'ordering': ('name',), 'verbose_name': 'Класс В легкого бетона', 'verbose_name_plural': 'Классы В легких бетонов'},
        ),
    ]
