# Generated by Django 3.0.3 on 2020-02-26 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_activity_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
                ('provider', models.ForeignKey(help_text='Выберите поставщика, которому принадлежит этот офис,торговая точка', on_delete=django.db.models.deletion.CASCADE, to='catalog.Provider')),
            ],
            options={
                'verbose_name': 'Торговая точка/офис',
                'verbose_name_plural': 'Торговые точки/офисы',
                'ordering': ('provider',),
            },
        ),
    ]
