# Generated by Django 3.0.3 on 2020-02-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='scheme_scale',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='scheme_scale',
        ),
    ]
