# Generated by Django 3.0.2 on 2020-02-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200218_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='standard_size',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='height',
            field=models.IntegerField(blank=True, help_text='Высота', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='max_bed_size',
            field=models.IntegerField(blank=True, help_text='Максимальный размер постели', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='min_bed_size',
            field=models.IntegerField(blank=True, help_text='Минимальный размер постели', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='name',
            field=models.CharField(blank=True, help_text='Торговое название, если есть', max_length=200),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='standart_size',
            field=models.ManyToManyField(blank=True, help_text='Выбрите размер НФ, которому соответствует изделие', to='catalog.RockWallMaterialStandardSize'),
        ),
    ]
