# Generated by Django 3.0.3 on 2020-02-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200227_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='heating_period_duration',
            field=models.IntegerField(blank=True, help_text='Продолжительность отопительного периода, сут', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='heating_period_temperature',
            field=models.IntegerField(blank=True, help_text='Средняя температура отопительного периода, град. C', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Выберите город', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.City'),
        ),
    ]
