# Generated by Django 2.1.4 on 2019-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20191112_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rockwallmaterialunit',
            options={'verbose_name': 'Единица стенового материала', 'verbose_name_plural': 'Единицы стеновых материалов'},
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='a_size',
            field=models.IntegerField(blank=True, help_text='Введите размеры, если они нестандарнтые', null=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='b_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='c_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='thermal_conductivity',
            field=models.IntegerField(blank=True, help_text='Введите коэффициент теплопроводности', null=True),
        ),
    ]
