# Generated by Django 3.0.2 on 2020-02-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200218_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasonryBonding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Краткое название способа скрепления кладки', max_length=200)),
                ('description', models.CharField(help_text='Подробное описание способа скрепления кладки', max_length=200)),
            ],
            options={
                'verbose_name': 'Способ скрепления кладки',
                'verbose_name_plural': 'Способы скрепления кладки',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='reinforcement_type',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='binding_solution',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='binding_solution',
            field=models.ForeignKey(blank=True, help_text='Выберите тип специального клея для данного материала', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BinderSolutionType'),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='brand',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите основной бренд (например, Wienerberger)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductBrand'),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='class_b',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='class_b',
            field=models.ForeignKey(blank=True, help_text='Выберите стандартный класс В для данного материала, если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ClassBLight'),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='height',
            field=models.IntegerField(blank=True, help_text='Высота, мм', null=True),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='mark_d',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='mark_d',
            field=models.ForeignKey(blank=True, help_text='Выберите стандартную марку D для данного материала, если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MarkD'),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='max_bed_size',
            field=models.IntegerField(blank=True, help_text='Больший размер постели, мм', null=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='min_bed_size',
            field=models.IntegerField(blank=True, help_text='Меньший размер постели, мм', null=True),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='producer',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='producer',
            field=models.ForeignKey(blank=True, help_text='Выберите производителя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DirectProducer'),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='standart_size',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='standart_size',
            field=models.ForeignKey(blank=True, help_text='Выбрите размер НФ, которому соответствует изделие', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.RockWallMaterialStandardSize'),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='trade_mark',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='trade_mark',
            field=models.ForeignKey(blank=True, help_text='Выберите торговую марку изделия (например, Porotherm 44)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.TradeMark'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='bounding',
            field=models.ManyToManyField(help_text='Выберите способы скрепления кладки', to='catalog.MasonryBonding'),
        ),
    ]
