# Generated by Django 3.0.2 on 2020-02-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200227_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='city',
        ),
        migrations.AddField(
            model_name='profile',
            name='outlet',
            field=models.ManyToManyField(help_text='Если пользователь - подрядчик, выберите торговую точку', to='catalog.Outlet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_or_additional',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('contractor', 'Подрядчик')], default='customer', help_text='Тип пользователя', max_length=10),
        ),
    ]
