# Generated by Django 2.1.4 on 2019-11-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191112_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='standard_size',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='standard_size',
            field=models.ForeignKey(blank=True, default=2, help_text='Выберите тип стандартного размера, если есть', on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialStandardSize'),
            preserve_default=False,
        ),
    ]
