# Generated by Django 3.0.2 on 2020-02-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200228_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='outlet',
        ),
        migrations.AddField(
            model_name='profile',
            name='provider',
            field=models.ManyToManyField(help_text='Выберите поставщика, которому принадлежит этот офис,торговая точка', to='catalog.Provider'),
        ),
        migrations.AlterField(
            model_name='city',
            name='heating_period_temperature',
            field=models.FloatField(blank=True, help_text='РАЗДЕЛИТЕЛЬ - ТОЧКА. Средняя температура отопительного периода, град. C. столбец 12', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_or_additional',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('outlet', 'Торговая точка ')], default='customer', help_text='Тип пользователя', max_length=10),
        ),
    ]
