# Generated by Django 2.1.4 on 2019-11-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191112_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='standard_size',
            field=models.ForeignKey(blank=True, help_text='Выберите тип стандартного размера, если есть', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialStandardSize'),
        ),
    ]
