# Generated by Django 3.0.2 on 2020-02-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200228_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Outlet',
        ),
    ]
