# Generated by Django 2.1.4 on 2019-11-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20191114_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='type_size',
        ),
        migrations.AddField(
            model_name='rockwallmaterialstandardsize',
            name='type_size',
            field=models.CharField(choices=[('bl', 'Блок'), ('br', 'Кирпич')], default='br', help_text='Тип материала по размеру: блок или кирпич', max_length=2),
        ),
    ]
