# Generated by Django 2.1.4 on 2019-11-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20191114_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rockwallmaterialstandardsize',
            old_name='type_size',
            new_name='size_type',
        ),
    ]
