# Generated by Django 3.0.2 on 2020-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200218_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rockwallmaterialunit',
            old_name='max_bed_size',
            new_name='greater_bed_size',
        ),
        migrations.RenameField(
            model_name='rockwallmaterialunit',
            old_name='min_bed_size',
            new_name='minor_bed_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='max_bed_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='min_bed_size',
        ),
        migrations.AddField(
            model_name='rockwallmaterialstandardsize',
            name='greater_bed_size',
            field=models.IntegerField(blank=True, help_text='Больший размер постели', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialstandardsize',
            name='minor_bed_size',
            field=models.IntegerField(blank=True, help_text='Меньший размер постели', null=True),
        ),
    ]
