# Generated by Django 3.0.2 on 2020-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_profile_primary_or_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='provider',
            field=models.ManyToManyField(blank=True, help_text='Выберите поставщика, которому принадлежит этот офис,торговая точка', to='catalog.Provider'),
        ),
        migrations.CreateModel(
            name='DecorativeBrickFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рисунка', max_length=200)),
                ('brand', models.ManyToManyField(blank=True, help_text='Бренд,который делает такой рисунок на своих кирпичах. М.б.несколько', to='catalog.Brand')),
            ],
            options={
                'verbose_name': 'Названея декоративной грани рядового кирпича',
                'verbose_name_plural': 'Названия декоративных граней рядовых кирпичей',
                'ordering': ('name',),
            },
        ),
    ]
