# Generated by Django 3.0.2 on 2020-02-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200228_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='face',
            field=models.ForeignKey(blank=True, help_text='Выберите название рисунка декоратьивной грани', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.DecorativeBrickFace'),
        ),
    ]
