# Generated by Django 3.0.2 on 2020-02-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200219_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialsizegrid',
            name='thickness_calc',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='thickness_calc',
            field=models.CharField(choices=[('mm', 'Только мм'), ('both', 'И мм. и шт.')], default='mm', help_text='Толщину стены можно считать в мм. и в штуках (н.р. в кирпичах) или строго в мм. (для материалов, которые можно ложить разными сторонами)', max_length=4),
        ),
    ]
