# Generated by Django 2.1.4 on 2019-11-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20191114_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='clamp',
            field=models.FloatField(verbose_name='Изготовление 1 хомута, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='const_expenditure',
            field=models.FloatField(verbose_name='Постоянные трудозатраты, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='formwork',
            field=models.FloatField(verbose_name='Установка 1кв.м. опалубки (ламфанера), чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='grillage_pour',
            field=models.FloatField(verbose_name='Заливка 1куб.м. бетона, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='ground_leveling',
            field=models.FloatField(verbose_name='Выравнивание 1кв.м. грунта, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='pile_frame',
            field=models.FloatField(verbose_name='Изготовление свайного каркаса, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='pile_pour',
            field=models.FloatField(verbose_name='Заливка 1 сваи, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='reinforcement_binding',
            field=models.FloatField(verbose_name='Вязка 1м арматуры ростверка, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='ruberoid_lining',
            field=models.FloatField(verbose_name='Гидроизоляция рубероидом 1пог.м. опалубки, чел.час'),
        ),
        migrations.AlterField(
            model_name='pilegrillagefoundationcost',
            name='transportation_procurement_cost',
            field=models.FloatField(verbose_name='Транспортно-заготовительные расходы, рублей'),
        ),
    ]
