# Generated by Django 2.1.4 on 2019-11-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20191114_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilegrillagefoundationcost',
            name='grillage_pour',
        ),
        migrations.RemoveField(
            model_name='pilegrillagefoundationcost',
            name='ground_leveling',
        ),
        migrations.RemoveField(
            model_name='pilegrillagefoundationcost',
            name='ruberoid_lining',
        ),
        migrations.AddField(
            model_name='pilegrillagefoundationcost',
            name='length_costs',
            field=models.FloatField(default=1, verbose_name='Затраты, зависящие от длины ростверка, за 1 пог.м., чел.час'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilegrillagefoundationcost',
            name='square_costs',
            field=models.FloatField(default=1.0, verbose_name='Затраты, зависящие от площали ростверка, за 1 кв.м., чел.час'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilegrillagefoundationcost',
            name='volume_costs',
            field=models.FloatField(default=2, verbose_name='Затраты, зависящие от объема бетона ростверка, за 1 куб.м., чел.час'),
            preserve_default=False,
        ),
    ]
