# Generated by Django 3.0.2 on 2020-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200219_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfsize',
            name='identifier',
            field=models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True),
        ),
    ]
