# Generated by Django 3.0.2 on 2020-02-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200219_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='masonrybonding',
            name='load_distribution',
            field=models.CharField(choices=[('yes', 'Требуется'), ('no', 'Не требуется')], default='no', help_text='Усиление для распределения нагрузки', max_length=3),
        ),
    ]
