# Generated by Django 3.0.2 on 2020-02-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_masonrybonding_load_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinderSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название материала как в спецификации изготовителя', max_length=200)),
            ],
            options={
                'verbose_name': 'Специальный кладочный клей, растворы',
                'verbose_name_plural': 'Специальные кладочные клеи, растворы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название сетки как в спецификации изготовителя', max_length=200)),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите бренд (например, Wienerberger), если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductBrand')),
            ],
            options={
                'verbose_name': 'Сетка',
                'verbose_name_plural': 'Сетки',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='GridUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Название применения', max_length=200)),
            ],
            options={
                'verbose_name': 'Перечень применения строительных сеток',
                'verbose_name_plural': 'Перечень применения строительных сеток',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PorothermSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Наименование системы кладки, например, Porotherm 44, Porotherm 38', max_length=200)),
            ],
            options={
                'verbose_name': 'Система кладки Porotherm',
                'verbose_name_plural': 'Системы кладки Porotherm',
                'ordering': ('name',),
            },
        ),
        migrations.RenameModel(
            old_name='DirectProducer',
            new_name='Producer',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.RemoveField(
            model_name='trademark',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='trademarkseries',
            name='trademark',
        ),
        migrations.DeleteModel(
            name='WallMaterialType',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='size_grid',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='trade_mark',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='blind_hollow',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], default='no', help_text='Несквозные пустоты (для полнотелых кирпичей)', max_length=3),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='clinker',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], default='no', help_text='Клинкерный кирпич', max_length=3),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='material',
            field=models.CharField(choices=[('clay', 'глиняный'), ('silicate', 'силикатный'), ('gas_concrete', 'газобетонный'), ('ceramsite_concrete', 'керамзитобетонный')], default='clay', help_text='Материал изделия', max_length=18),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='polish',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], default='no', help_text='Шлифованный', max_length=3),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='quantity_per_pallet',
            field=models.IntegerField(blank=True, help_text='Количество на поддоне', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='tongue_and_groove',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], default='no', help_text='Пазогребневая система', max_length=3),
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='binding_solution',
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите бренд, например, Porotherm', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.ProductBrand'),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='name',
            field=models.CharField(choices=[('brick', 'Кирпич'), ('rock', 'Камень'), ('block', 'Блок')], default='brick', help_text='Вид изделия', max_length=5),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='purpose',
            field=models.CharField(choices=[('wall', 'Рядовой '), ('fasade', 'Лицевой'), ('decor_edge', 'Рядовой с декоративной гранью')], default='wall', help_text='Назначение: рядовой, лицевой', max_length=10),
        ),
        migrations.DeleteModel(
            name='BinderSolutionType',
        ),
        migrations.DeleteModel(
            name='RockWallMaterialSizeGrid',
        ),
        migrations.DeleteModel(
            name='TradeMark',
        ),
        migrations.DeleteModel(
            name='TradeMarkSeries',
        ),
        migrations.AddField(
            model_name='grid',
            name='usage',
            field=models.ManyToManyField(help_text='Выберите применение данной сетки', related_name='secondary_activity', to='catalog.GridUsage'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='porotherm_system',
            field=models.ManyToManyField(blank=True, help_text='Выберите конкретную систему для Porotherm', to='catalog.PorothermSystem'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='binding_solution',
            field=models.ManyToManyField(blank=True, help_text='Выберите специальный клей для данного материала', to='catalog.BinderSolution'),
        ),
    ]
