# Generated by Django 2.1.7 on 2019-12-10 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0019_auto_20191119_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_scale', models.IntegerField(blank=True, default=25, null=True, verbose_name='Начальный масштаб схемы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Castomization',
            new_name='Customization',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='castomization',
            new_name='customization',
        ),
    ]
