# Generated by Django 3.0.2 on 2020-02-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200228_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rockwallmaterialprice',
            options={'ordering': ('name',), 'verbose_name': 'Цены каменные стеновые материалы', 'verbose_name_plural': 'Цены каменные стеновые материалы'},
        ),
    ]
