# Generated by Django 3.0.2 on 2020-02-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20200221_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classb',
            options={'ordering': ('name',), 'verbose_name': 'Класс В бетона', 'verbose_name_plural': 'Классы В бетонов'},
        ),
    ]
