# Generated by Django 2.1.7 on 2019-12-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_auto_20191210_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customization',
            options={'verbose_name': 'Индивидуальные настройки проекта', 'verbose_name_plural': 'Индивидуальные настройки проектов'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
