# Generated by Django 3.0.3 on 2020-03-05 10:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20200303_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='scheme',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
