# Generated by Django 3.0.2 on 2020-03-12 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_plan_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCityCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.City')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialUnit')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan')),
            ],
            options={
                'verbose_name': 'Минимальная цена строительства',
                'verbose_name_plural': 'Минимальные цены строительства',
                'ordering': ['material', 'cost'],
            },
        ),
    ]
