# Generated by Django 3.0.2 on 2020-03-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_plancitycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
    ]
