# Generated by Django 3.0.3 on 2020-11-04 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '0002_auto_20201104_1244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CottageCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название коттежного поселка', max_length=200)),
                ('clarify', models.CharField(help_text='Уточнение на случай, если КП с таким названием несколько', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeologicalSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legal.LegalEntity')),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер скважины', unique=True)),
                ('bearing_resistance_pile_2000_300', models.FloatField(help_text='Несущая способность сваи глубиной 2 метра и диаметром 300мм')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.GeologicalSurvey', verbose_name='Геологическое исследование')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.IntegerField(help_text='Кадастровый номер')),
                ('cottage_community', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.CottageCommunity')),
            ],
        ),
        migrations.AddField(
            model_name='geologicalsurvey',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='land.Land'),
        ),
        migrations.CreateModel(
            name='EngineeringLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Номер слоя в скважине (уникален)', unique=True)),
                ('sand_vs_clay', models.CharField(choices=[('s', 'Песок'), ('l', 'Супесь/суглинок'), ('c', 'Глина')], default='l', help_text='Описание грунта', max_length=1)),
                ('sand', models.CharField(choices=[('c', 'Крупный и средней крупности песок'), ('f', 'Мелкий песок'), ('d', 'Пылеватый песок')], default='f', help_text='Описание песка', max_length=1)),
                ('porosity', models.FloatField(help_text='Коэффициент пористости')),
                ('IL', models.FloatField(help_text='Показатель текучести - для глинистых')),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.SurveyWell', verbose_name='Скважина')),
            ],
        ),
    ]
