# Generated by Django 3.0.3 on 2020-11-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeringlayer',
            name='debris',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='n', help_text='Крупнообломочный строительный мусор', max_length=1),
        ),
        migrations.AddField(
            model_name='engineeringlayer',
            name='height',
            field=models.IntegerField(default=0, help_text='Высота в сантиметрах устья скважины относительно других скважин, если есть. Самая низкая = 0'),
        ),
        migrations.AddField(
            model_name='engineeringlayer',
            name='non_consolidated',
            field=models.CharField(choices=[('y', 'Да'), ('n', 'Нет')], default='n', help_text='Насыпной неконсолидированный', max_length=1),
        ),
        migrations.AddField(
            model_name='engineeringlayer',
            name='power',
            field=models.FloatField(default=0, help_text='Мощность слоя, в метрах'),
        ),
        migrations.AlterField(
            model_name='engineeringlayer',
            name='sand',
            field=models.CharField(choices=[('n', 'Ничего из перечисленного'), ('c', 'Крупный и средней крупности песок'), ('f', 'Мелкий песок'), ('d', 'Пылеватый песок')], default='n', help_text='Описание песка', max_length=1),
        ),
        migrations.AlterField(
            model_name='engineeringlayer',
            name='sand_vs_clay',
            field=models.CharField(choices=[('n', 'Органический'), ('s', 'Песок'), ('l', 'Супесь/суглинок'), ('c', 'Глина')], default='n', help_text='Описание грунта инженерного слоя', max_length=1),
        ),
    ]
