# Generated by Django 3.0.3 on 2020-11-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0002_auto_20201104_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='owner',
            field=models.OneToOneField(help_text='Собственники участка', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
