# Generated by Django 3.0.3 on 2020-11-05 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0004_auto_20201104_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='cadastral_number',
            field=models.CharField(max_length=20, verbose_name='Кадастровый номер'),
        ),
        migrations.AlterField(
            model_name='land',
            name='cottage_community',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='land.CottageCommunity', verbose_name='Коттеджный посёлок'),
        ),
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Собственник участка'),
        ),
    ]
