# Generated by Django 3.0.3 on 2020-11-05 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('land', '0005_auto_20201105_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='land',
            options={'verbose_name': 'Участок', 'verbose_name_plural': 'Участки'},
        ),
        migrations.AlterField(
            model_name='land',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Собственник участка'),
        ),
    ]
