# Generated by Django 3.0.3 on 2020-11-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal', '0002_auto_20201104_1244'),
        ('land', '0006_auto_20201105_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='geologicalsurvey',
            name='legal_entity',
            field=models.OneToOneField(help_text='Есть резон хранить и пользователя и организацию, от имени которой он проводит исследование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entity', to='legal.LegalEntity', verbose_name='Организация-исполнитель'),
        ),
        migrations.AlterField(
            model_name='cottagecommunity',
            name='clarify',
            field=models.CharField(max_length=200, verbose_name='Уточнение на случай, если КП с таким названием несколько'),
        ),
        migrations.AlterField(
            model_name='cottagecommunity',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название коттежного поселка'),
        ),
        migrations.AlterField(
            model_name='engineeringlayer',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота в сантиметрах устья скважины относительно других скважин, если есть. Самая низкая = 0'),
        ),
        migrations.AlterField(
            model_name='engineeringlayer',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер слоя в скважине (уникален)'),
        ),
        migrations.AlterField(
            model_name='engineeringlayer',
            name='power',
            field=models.FloatField(default=0, verbose_name='Мощность слоя, в метрах'),
        ),
        migrations.AlterField(
            model_name='geologicalsurvey',
            name='contractor',
            field=models.OneToOneField(help_text='Есть резон хранить и пользователя и организацию, от имени которой он проводит исследование', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь-исполнитель'),
        ),
        migrations.AlterField(
            model_name='geologicalsurvey',
            name='customer',
            field=models.OneToOneField(help_text='Сделать здесь поиск пользователя по номеру телефона', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик изыскания'),
        ),
        migrations.AlterField(
            model_name='geologicalsurvey',
            name='land',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='land.Land', verbose_name='Участок'),
        ),
        migrations.AlterField(
            model_name='surveywell',
            name='bearing_resistance_pile_2000_300',
            field=models.FloatField(verbose_name='Несущая способность сваи глубиной 2 метра и диаметром 300мм'),
        ),
        migrations.AlterField(
            model_name='surveywell',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер скважины'),
        ),
    ]
