# Generated by Django 3.0.3 on 2020-02-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='brand_0',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='brand_0',
        ),
        migrations.DeleteModel(
            name='Brand_0',
        ),
    ]
