# Generated by Django 3.0.2 on 2020-02-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите страну', max_length=200, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='producer',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Выберите бренд (например, Wienerberger), если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(help_text='Введите производителя материала. Например, Кощаковский, Чайковский и т.д.', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите регион', max_length=200, unique=True)),
                ('country', models.ForeignKey(blank=True, help_text='Страна', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Country')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Регион', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Region'),
        ),
    ]
