# Generated by Django 3.0.2 on 2020-02-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinderSolutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifiter', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите тип связующего раствора. Например, цементный раствор, клей на цементной основе и т.д.', max_length=200)),
            ],
            options={
                'verbose_name': 'Тип связующего раствора',
                'verbose_name_plural': 'Типы связующих растворов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RockWallMaterialColloquialName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите общепринятое название материала - кирпич красный полнотелый, блок газобетонный', max_length=200)),
                ('size_type', models.CharField(choices=[('brick', 'Кирпич'), ('block', 'Блок')], help_text='Типоразмер: кирпич или блок', max_length=5)),
            ],
            options={
                'verbose_name': 'Общепринятое название материала',
                'verbose_name_plural': 'Общепринятое название материала',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WallReinforcementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите тип армирования', max_length=200)),
            ],
            options={
                'verbose_name': 'Тип армирования',
                'verbose_name_plural': 'Типы армирования',
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='body_type',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='a_size',
            field=models.IntegerField(blank=True, help_text='Введите размеры, если они нестандарнтые. Максимальный размер', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='b_size',
            field=models.IntegerField(blank=True, help_text='Введите размеры, если они нестандарнтые. Средний размер', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='c_size',
            field=models.IntegerField(blank=True, help_text='Введите размеры, если они нестандарнтые. Минимальный размер', null=True),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='brick_type',
            field=models.CharField(blank=True, choices=[('f', 'Облицовочный'), ('o', 'Рядовой'), ('m', 'Рядовой c декоративной гранью'), ('p', 'Перегородочный')], help_text='Тип кирпича - рядовой или облицовочный', max_length=1),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='primary_or_additional',
            field=models.CharField(choices=[('p', 'Основной'), ('a', 'Доборный')], default='primary', help_text='Тип элемента: основной или доборный', max_length=1),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='binding_solution',
            field=models.ManyToManyField(help_text='Выберите тип связующего для данного материала', to='catalog.BinderSolutionType'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='colloquial_name',
            field=models.ForeignKey(blank=True, help_text='Выберите общепринятое название материала', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialColloquialName'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='reinforcement_type',
            field=models.ManyToManyField(help_text='Выберите тип армирования для данного материала', to='catalog.WallReinforcementType'),
        ),
    ]
