# Generated by Django 3.0.3 on 2020-06-05 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0009_auto_20200605_1718'),
        ('catalog', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacadeMaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название для понимания', max_length=200, unique=True)),
                ('identifier', models.CharField(choices=[('brick', 'Облицовочный кирпич'), ('plaster', 'Штукатурка'), ('tile', 'Плитка')], default='brick', help_text='Идентификатор для использования в коде', max_length=20)),
            ],
            options={
                'verbose_name': 'Тип фасадного (облицовочного) материала',
                'verbose_name_plural': 'Типы фасадных (облицовочных) материалов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Shell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roof_material_id', models.IntegerField(help_text='id материала кровли из той таблицы типа материала, который выбрал пользователь')),
                ('soffit_style', models.CharField(choices=[('horizontal', 'Горизонтальный'), ('inclined', 'Наклонный')], default='horizontal', help_text='Стиль нижней части свеса', max_length=20)),
                ('wall_material_0_id', models.IntegerField(help_text='id материала из той таблицы типа материала, который выбрал пользователь')),
                ('socle_material_id', models.IntegerField(help_text='id материала из той таблицы типа материала, который выбрал пользователь')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('roof_material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.RoofCoverType', verbose_name='Тип материала кровли')),
                ('socle_material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socle_material_type', to='catalog.FacadeMaterialType', verbose_name='Тип материала облицовки цоколя')),
                ('wall_material_type_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wall_material_type', to='catalog.FacadeMaterialType', verbose_name='Тип материала облицовки основной части стен')),
            ],
            options={
                'verbose_name': 'Шаблон оформления фасада',
                'verbose_name_plural': 'Шаблоны оформления фасада',
            },
        ),
    ]
