# Generated by Django 3.0.3 on 2020-09-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200908_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='fasade_wall_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
