# Generated by Django 3.0.2 on 2020-02-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200221_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='code',
            field=models.IntegerField(blank=True, help_text='Цифровой код региона', max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='Введите город', max_length=200),
        ),
    ]
