# Generated by Django 3.0.2 on 2020-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rockwallmaterialcolloquialname_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='body_type',
            field=models.CharField(choices=[('solid', 'Полнотелый'), ('hollow', 'Пустотелый')], default='solid', help_text='Пустотелый или полнотелый', max_length=6),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='purpose',
            field=models.CharField(choices=[('w', 'Стеновой'), ('f', 'Фасадный'), ('d', 'Стеновой с декоративной гранью')], default='w', help_text='Назначение: стеновой, фасадный', max_length=1),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='size_type',
            field=models.CharField(choices=[('brick', 'Кирпич'), ('block', 'Блок')], default='brick', help_text='Типоразмер: кирпич или блок', max_length=5),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='colloquial_name',
            field=models.CharField(choices=[('keramik_hollow_brick', 'Керамический пустотелый кирпич'), ('aerated_concrete_block', 'Газобетонный блок')], default='w', help_text='Общепринятое название материала', max_length=30),
        ),
        migrations.DeleteModel(
            name='RockWallMaterialColloquialName',
        ),
    ]
