# Generated by Django 3.0.2 on 2020-02-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200221_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Выберите город', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.City'),
        ),
    ]
