# Generated by Django 3.0.3 on 2020-08-13 05:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_facadematerialtype_shell'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacadeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('material_id', models.IntegerField(blank=True, null=True)),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.FacadeMaterialType', verbose_name='Автор')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Plan')),
            ],
            options={
                'verbose_name': 'Сектор отделки фасада',
                'verbose_name_plural': 'Сектора отделки фасада',
                'ordering': ('material_type', 'material_id'),
            },
        ),
    ]
