# Generated by Django 3.0.2 on 2020-02-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200218_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='a_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='b_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='c_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialstandardsize',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='a_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='b_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='brick_type',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='c_size',
        ),
        migrations.AddField(
            model_name='rockwallmaterialstandardsize',
            name='height',
            field=models.IntegerField(blank=True, help_text='Высота', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialstandardsize',
            name='max_bed_size',
            field=models.IntegerField(blank=True, help_text='Максимальный размер постели', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialstandardsize',
            name='min_bed_size',
            field=models.IntegerField(blank=True, help_text='Минимальный размер постели', null=True),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='double_install',
            field=models.CharField(choices=[('no', 'Нет'), ('yes', 'Да')], default='no', help_text='Допустима ли установка и на постель и на ребро', max_length=3),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='colloquial_name',
            field=models.CharField(choices=[('keramik_hollow_brick', 'Керамический пустотелый кирпич'), ('aerated_concrete_block', 'Газобетонный блок')], default='keramik_hollow_brick', help_text='Общепринятое название материала', max_length=30),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='primary_or_additional',
            field=models.CharField(choices=[('primary', 'Основной'), ('additional', 'Доборный')], default='primary', help_text='Тип элемента: основной или доборный', max_length=10),
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='purpose',
            field=models.CharField(choices=[('wall', 'Стеновой'), ('fasade', 'Фасадный'), ('decor_edge', 'Стеновой с декоративной гранью')], default='w', help_text='Назначение: стеновой, фасадный', max_length=10),
        ),
    ]
