# Generated by Django 2.1.4 on 2019-11-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191112_1706'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producer',
            new_name='DirectProducer',
        ),
    ]
