# Generated by Django 2.1.4 on 2019-11-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191112_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rockwallmaterialunit',
            options={},
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='application',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='binding_solution',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='reinforcement_type',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='wall_material_type',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='body_type',
            field=models.CharField(choices=[('r', 'Полнотелый красный'), ('s', 'Полнотелый силикатный'), ('h', 'Пустотелый керамический'), ('a', 'Газобетонный'), ('k', 'Керамзитобетонный')], default='r', help_text='Тип кирпича или блока', max_length=1),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='brand',
            field=models.ManyToManyField(blank=True, help_text='Выберите основной бренд (например, Wienerberger)', to='catalog.ProductBrand'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='brick_type',
            field=models.CharField(blank=True, choices=[('f', 'Облицовочный'), ('o', 'Рядовой'), ('m', 'Рядовой c гранью под облицовку')], help_text='Тип кирпича - рядовой или облицовочный', max_length=1),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='producer',
            field=models.ManyToManyField(blank=True, help_text='Выберите производителя', to='catalog.DirectProducer'),
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='trade_mark',
            field=models.ManyToManyField(blank=True, help_text='Выберите торговую марку изделия (например, Porotherm 44)', to='catalog.TradeMark'),
        ),
        migrations.DeleteModel(
            name='BinderSolutionType',
        ),
        migrations.DeleteModel(
            name='WallReinforcementType',
        ),
    ]
