# Generated by Django 3.0.2 on 2020-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200218_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='colloquial_name',
            field=models.CharField(choices=[('keramik_hollow_brick', 'Керамический пустотелый кирпич'), ('aerated_concrete_block', 'Газобетонный блок')], help_text='Общепринятое название материала', max_length=30),
        ),
    ]
