# Generated by Django 3.0.2 on 2020-02-18 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200218_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='mark_m',
        ),
        migrations.AddField(
            model_name='rockwallmaterialunit',
            name='mark_m',
            field=models.ForeignKey(blank=True, help_text='Выберите стандартную марку М для данного материала, если есть', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.MarkM'),
        ),
    ]
