# Generated by Django 3.0.3 on 2020-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200227_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='heating_period_duration',
            field=models.IntegerField(blank=True, help_text='Продолжительность отопительного периода, сут. СНиП 23-01-99 "Строительная климатология и геофизика". См. Таблица 1, столбец 11', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='heating_period_temperature',
            field=models.FloatField(blank=True, help_text='Средняя температура отопительного периода, град. C. столбец 12', null=True),
        ),
    ]
