# Generated by Django 3.0.2 on 2020-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200218_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='bounding',
            field=models.ManyToManyField(blank=True, help_text='Выберите способы скрепления кладки', null=True, to='catalog.MasonryBonding'),
        ),
    ]
