# Generated by Django 3.0.2 on 2020-02-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200218_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='standart_size',
        ),
    ]
