# Generated by Django 2.1.4 on 2019-11-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20191114_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='a_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='b_size',
        ),
        migrations.RemoveField(
            model_name='rockwallmaterialunit',
            name='c_size',
        ),
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='standard_size',
            field=models.ForeignKey(blank=True, help_text='Выберите стандартный размер', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.RockWallMaterialStandardSize'),
        ),
    ]
