# Generated by Django 3.0.2 on 2020-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_rockwallmaterialunit_standart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='bounding',
            field=models.ManyToManyField(blank=True, help_text='Выберите способы скрепления кладки', to='catalog.MasonryBonding'),
        ),
    ]
