# Generated by Django 3.0.2 on 2020-02-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_auto_20200228_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rockwallmaterialprice',
            options={'ordering': ('name',), 'permissions': (('can_set_material_price', 'Ввод цен на материалы'),), 'verbose_name': 'Цены каменные стеновые материалы', 'verbose_name_plural': 'Цены каменные стеновые материалы'},
        ),
    ]
