# Generated by Django 3.0.3 on 2020-03-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200228_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='var_name',
            new_name='identifier',
        ),
    ]
