# Generated by Django 3.0.2 on 2020-03-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_plan_finalized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='finalized',
            new_name='checked',
        ),
    ]
