# Generated by Django 3.0.2 on 2020-02-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_rockwallmaterialunit_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockwallmaterialunit',
            name='thermal_conductivity',
            field=models.FloatField(blank=True, help_text='Введите коэффициент теплопроводности', null=True),
        ),
        migrations.CreateModel(
            name='Insulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thermal_conductivity', models.FloatField(blank=True, help_text='Введите коэффициент теплопроводности', null=True)),
                ('mat_type', models.CharField(choices=[('xps', 'XPS'), ('rock_wool', 'Минеральная вата')], default='xps', help_text='Тип утеплителя', max_length=9)),
                ('thick', models.CharField(choices=[('20', '20 мм'), ('30', '30 мм'), ('50', '50 мм'), ('100', '100 мм')], default='20', help_text='Толщина', max_length=3)),
                ('brand', models.ForeignKey(blank=True, help_text='Выберите главный бренд, например, Ursa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand')),
            ],
            options={
                'verbose_name': 'Утеплитель',
                'verbose_name_plural': 'Утеплители',
                'ordering': ('brand',),
            },
        ),
    ]
