# Generated by Django 3.0.2 on 2020-02-28 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_rockwallmaterialprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rockwallmaterialprice',
            options={'ordering': ('name',), 'verbose_name': 'Цены каменные стеновые материалы', 'verbose_name_plural': 'Цены каменные стеновые материалы'},
        ),
        migrations.CreateModel(
            name='InsulationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Insulation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цены утеплители',
                'verbose_name_plural': 'Цены утеплители',
                'ordering': ('name',),
            },
        ),
    ]
