# Generated by Django 3.0.3 on 2020-09-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecorativeBrickFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рисунка', max_length=200)),
                ('brand', models.ManyToManyField(blank=True, help_text='Бренд,который делает такой рисунок на своих кирпичах. М.б.несколько', to='brands.Brand')),
            ],
            options={
                'verbose_name': 'Названея декоративной грани рядового кирпича',
                'verbose_name_plural': 'Названия декоративных граней рядовых кирпичей',
                'ordering': ('name',),
            },
        ),
    ]
