# Generated by Django 3.0.3 on 2020-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите класс В', max_length=5)),
            ],
            options={
                'verbose_name': 'Класс В бетона',
                'verbose_name_plural': 'Классы В бетонов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClassАverageDensity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите класс средней плотности', max_length=5)),
            ],
            options={
                'verbose_name': 'Класс средней плотности',
                'verbose_name_plural': 'Классы средней плотности',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите марку D', max_length=5)),
            ],
            options={
                'verbose_name': 'Марка D',
                'verbose_name_plural': 'Марки D',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите марку морозостойкости F', max_length=5)),
            ],
            options={
                'verbose_name': 'Марка морозостойкости F',
                'verbose_name_plural': 'Марки морозостойкости F',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MarkM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите марку М', max_length=5)),
            ],
            options={
                'verbose_name': 'Марка М',
                'verbose_name_plural': 'Марки М',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='NFSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='default_identifier', help_text='Уникальный неизменяемый идентификатор (только латинские символы)', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Введите название размера', max_length=200)),
                ('greater_bed_size', models.IntegerField(blank=True, help_text='Больший размер постели (длина), мм', null=True)),
                ('minor_bed_size', models.IntegerField(blank=True, help_text='Меньший размер постели (ширина), мм', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Высота (толщина), мм', null=True)),
            ],
            options={
                'verbose_name': 'Размер НФ',
                'verbose_name_plural': 'Размеры НФ',
                'ordering': ('name',),
            },
        ),
    ]
